"""
Voice warnings generated by a local language model.

Supported back ends (both run on the local machine):
  * Ollama            - provider "ollama", base URL http://localhost:11434
  * OpenAI-compatible - provider "openai", e.g. LM Studio (http://localhost:1234/v1)
                        or llama.cpp server (http://localhost:8080/v1)

If the model server is unreachable or slow, a pre-written line is used instead
so the guardian never goes silent.
"""
import os
import re
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from typing import Callable

import httpx

from data.fallback_messages import get_fallback_message
from services.settings_service import AISettings, settings_service


class AIError(RuntimeError):
    pass


# On CPU-only machines the model and the person detector compete for cores. Giving the
# model half of them keeps the camera feed and detection responsive while it is talking.
LLM_THREADS = max(2, (os.cpu_count() or 4) // 2)


SITUATIONS = {
    1: "An unrecognised person has just appeared on camera. Greet them and ask them to identify themselves or state their business.",
    2: "The person has stayed for {seconds} seconds. Tell them clearly that this is private property and that they are being recorded.",
    3: "The person has been here for {seconds} seconds. Tell them the owner has been alerted, the footage is saved, and they must leave now.",
    4: "Final warning: the alarm is sounding and the person has ignored repeated warnings for {seconds} seconds. Order them to leave immediately.",
}
PANIC_SITUATION = "The owner has raised the alarm manually. Tell the person on camera that the alarm is active, they are being recorded, and they must leave immediately."

_THINK_RE = re.compile(r"<think>.*?</think>", re.DOTALL | re.IGNORECASE)
_LABEL_RE = re.compile(r"^\s*(guardian|ai|security|system|assistant|voice)\s*:\s*", re.IGNORECASE)


def _tone(cfg: AISettings) -> str:
    if cfg.intimidation >= 67:
        tone = "stern and intimidating"
    elif cfg.intimidation >= 34:
        tone = "firm and authoritative"
    else:
        tone = "calm and polite"
    if cfg.humor >= 67:
        tone += ", with sarcastic wit"
    elif cfg.humor >= 34:
        tone += ", with a touch of dry humour"
    return tone


def build_system_prompt(cfg: AISettings) -> str:
    return (
        "You are the voice of a property's security system, speaking through a loudspeaker "
        "to a person seen on camera. Speak directly to that person.\n"
        f"Tone: {_tone(cfg)}.\n"
        "Rules: reply with one or two short sentences, under 35 words in total. "
        "Plain spoken English only: no quotation marks, emojis, stage directions, lists or labels. "
        "Do not introduce yourself and never give yourself a name or job title. "
        "Only state facts you were given; never invent police, guards, dogs, weapons or damage."
    )


def clean_response(text: str) -> str:
    text = _THINK_RE.sub("", text or "")
    text = text.replace("*", "").strip()
    lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
    text = " ".join(lines)
    text = _LABEL_RE.sub("", text)
    text = text.strip().strip('"').strip("'").strip("“”").strip()
    text = re.sub(r"\s+", " ", text)
    # Keep it short enough to speak in a few seconds.
    sentences = re.split(r"(?<=[.!?])\s+", text)
    text = " ".join(sentences[:2])
    return text[:280].strip()


class AIService:
    def __init__(self, settings=settings_service):
        self.settings = settings
        self._executor = ThreadPoolExecutor(max_workers=1, thread_name_prefix="ai")
        self._busy = threading.Event()
        self._model_cache: tuple[tuple, str, float] | None = None
        self.last_error: str | None = None
        self.last_latency_ms: int | None = None
        self.last_source: str | None = None  # "llm" or "fallback"
        self.last_model: str | None = None
        settings.on_change(lambda old, new: self._invalidate() if old.ai != new.ai else None)

    def _invalidate(self):
        self._model_cache = None
        self.last_error = None

    # ---- server access -------------------------------------------------
    @staticmethod
    def _base(cfg: AISettings) -> str:
        return cfg.base_url.strip().rstrip("/")

    @staticmethod
    def _headers(cfg: AISettings) -> dict:
        return {"Authorization": f"Bearer {cfg.api_key}"} if cfg.api_key else {}

    def list_models(self, cfg: AISettings | None = None) -> list[str]:
        cfg = cfg or self.settings.get().ai
        try:
            if cfg.provider == "ollama":
                r = httpx.get(f"{self._base(cfg)}/api/tags", timeout=5)
                r.raise_for_status()
                return sorted(m["name"] for m in r.json().get("models", []))
            r = httpx.get(f"{self._base(cfg)}/models", headers=self._headers(cfg), timeout=5)
            r.raise_for_status()
            return sorted(m["id"] for m in r.json().get("data", []))
        except httpx.ConnectError as exc:
            raise AIError(f"Cannot reach {cfg.provider} at {cfg.base_url}. Is it running?") from exc
        except httpx.HTTPStatusError as exc:
            raise AIError(f"{cfg.provider} returned HTTP {exc.response.status_code} for {exc.request.url}") from exc
        except (httpx.HTTPError, ValueError, KeyError) as exc:
            raise AIError(f"Model list request failed: {exc}") from exc

    def resolve_model(self, cfg: AISettings) -> str:
        key = (cfg.provider, self._base(cfg), cfg.model)
        if self._model_cache and self._model_cache[0] == key and time.time() - self._model_cache[2] < 60:
            return self._model_cache[1]
        models = self.list_models(cfg)
        if not models:
            hint = "ollama pull llama3.2:3b" if cfg.provider == "ollama" else "load a model in your server"
            raise AIError(f"No models installed. Run: {hint}")
        if cfg.model:
            # Ollama accepts "llama3.2" for "llama3.2:latest"
            matches = [m for m in models if m == cfg.model or m == f"{cfg.model}:latest"]
            if not matches:
                raise AIError(f"Model '{cfg.model}' is not installed. Available: {', '.join(models[:8])}")
            model = matches[0]
        else:
            model = models[0]
        self._model_cache = (key, model, time.time())
        return model

    def _chat(self, cfg: AISettings, model: str, messages: list[dict]) -> str:
        timeout = httpx.Timeout(cfg.timeout_seconds, connect=5)
        if cfg.provider == "ollama":
            r = httpx.post(f"{self._base(cfg)}/api/chat", timeout=timeout, json={
                "model": model,
                "messages": messages,
                "stream": False,
                "keep_alive": "30m",
                "options": {"num_predict": 90, "temperature": 0.7, "num_thread": LLM_THREADS},
            })
            r.raise_for_status()
            return r.json()["message"]["content"]
        r = httpx.post(f"{self._base(cfg)}/chat/completions", headers=self._headers(cfg), timeout=timeout, json={
            "model": model,
            "messages": messages,
            "max_tokens": 90,
            "temperature": 0.8,
        })
        r.raise_for_status()
        return r.json()["choices"][0]["message"]["content"]

    # ---- generation ----------------------------------------------------
    def build_messages(self, cfg: AISettings, level: int, seconds: int, manual: bool, said: list[str]) -> list[dict]:
        situation = PANIC_SITUATION if manual else SITUATIONS.get(level, SITUATIONS[1]).format(seconds=seconds)
        if said:
            situation += " Do not repeat these earlier lines: " + " | ".join(said[-3:])
        return [
            {"role": "system", "content": build_system_prompt(cfg)},
            {"role": "user", "content": situation},
        ]

    def generate_warning(self, level: int, seconds: int = 0, manual: bool = False, said: list[str] | None = None) -> dict:
        cfg = self.settings.get().ai
        started = time.time()
        try:
            model = self.resolve_model(cfg)
            text = clean_response(self._chat(cfg, model, self.build_messages(cfg, level, seconds, manual, said or [])))
            if not text:
                raise AIError("Model returned an empty reply")
            self.last_error, self.last_source, self.last_model = None, "llm", model
        except (AIError, httpx.HTTPError, KeyError, ValueError) as exc:
            msg = str(exc) or exc.__class__.__name__
            if isinstance(exc, httpx.TimeoutException):
                msg = f"Model did not answer within {cfg.timeout_seconds}s"
            self.last_error, self.last_source, model = msg, "fallback", None
            print(f"[ai] Using fallback line: {msg}")
            text = get_fallback_message(level)
        self.last_latency_ms = int((time.time() - started) * 1000)
        return {"text": text, "source": self.last_source, "model": model, "latency_ms": self.last_latency_ms, "error": self.last_error}

    def request_warning(self, callback: Callable[[dict], None], **kwargs) -> bool:
        """Generate in the background. Returns False if a generation is already running."""
        if self._busy.is_set():
            return False
        self._busy.set()

        def run():
            try:
                callback(self.generate_warning(**kwargs))
            except Exception as exc:
                print(f"[ai] Warning task failed: {exc}")
            finally:
                self._busy.clear()

        self._executor.submit(run)
        return True

    def status(self) -> dict:
        cfg = self.settings.get().ai
        return {
            "provider": cfg.provider,
            "base_url": cfg.base_url,
            "model": self.last_model or cfg.model or None,
            "busy": self._busy.is_set(),
            "last_source": self.last_source,
            "last_error": self.last_error,
            "last_latency_ms": self.last_latency_ms,
        }

    def warm_up(self) -> None:
        """Load the model into memory in the background so the first warning is quick."""
        def run():
            cfg = self.settings.get().ai
            try:
                model = self.resolve_model(cfg)
                self._chat(cfg, model, [{"role": "user", "content": "Reply with: ready"}])
                self.last_model = model
                print(f"[ai] {cfg.provider} model '{model}' is loaded")
            except Exception as exc:
                self.last_error = str(exc)
                print(f"[ai] Model not ready: {exc}")
        threading.Thread(target=run, daemon=True, name="ai-warmup").start()


ai_service = AIService()
