// Writes src/theme.css: the colour tokens behind every Tailwind colour the dashboard uses, for both themes.
// Run with `node scripts/gen-theme.cjs` after changing the mapping below.
const fs = require('fs')
const path = require('path')
const colors = require('tailwindcss/colors')

const HUES = ['zinc', 'red', 'blue', 'amber', 'emerald', 'yellow', 'orange', 'cyan', 'indigo', 'green', 'sky']
const STEPS = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950']
// Light mode: which step (or colour) each step shows. Greys flip so backgrounds turn light and text dark;
// hues flip their pale and deep ends, keeping the strong 500-700 steps of buttons and badges.
const LIGHT_GREY = { 50: '950', 100: '900', 200: '800', 300: '700', 400: '600', 500: '500', 600: '400', 700: '300', 800: '200', 900: '#ffffff', 950: '100' }
const LIGHT_HUE = { 50: '950', 100: '900', 200: '800', 300: '700', 400: '600', 500: '500', 600: '600', 700: '700', 800: '200', 900: '100', 950: '50' }

const rgb = (hex) => [0, 2, 4].map((i) => parseInt(hex.replace('#', '').slice(i, i + 2), 16)).join(' ')
const tokens = (pick) =>
  HUES.map((h) => STEPS.map((s) => `--${h}-${s}: ${rgb(pick(h, s))};`).join(' ')).join('\n  ')
const dark = tokens((h, s) => colors[h][s])
const light = tokens((h, s) => {
  const m = (h === 'zinc' ? LIGHT_GREY : LIGHT_HUE)[s]
  return m.startsWith('#') ? m : colors[h][m]
})

fs.writeFileSync(
  path.join(__dirname, '..', 'src', 'theme.css'),
  `/* Generated by scripts/gen-theme.cjs. Every Tailwind colour reads one of these tokens, so a theme is a remapping
   of steps. .force-dark keeps dark tokens inside it, for text over video and camera pictures. */
:root,
.force-dark,
[data-theme='light'] .force-dark {
  color-scheme: dark;
  ${dark}
}

[data-theme='light'] {
  color-scheme: light;
  ${light}
}
`,
)
